[metadata]
name = passginity
version = 0.2.0
description = A configurable cryptographically secure password generator
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Topic :: Security

[options]
packages = find:
python_requires = >=3.8

[options.packages.find]
include =
    passginity*

[options.entry_points]
console_scripts =
    passginity = passginity.cli:main
